ALUMNOS_POR_AYUDANTE = {
    "Camilo Urzúa Gebauer": [
        "Pablo Abarca R.",
        "Andrés Ahumada C.",
        "Benjamín Alcaíno M.",
        "José I. Aliaga",
        "Andrés Araya",
        "Arturo Arias",
        "Juan Balboa Espinoza",
        "Benjamín Beissinger S.",
        "Antonia Berríos S.",
        "Francisco Cantillana S.",
        "Esperanza Cares O.",
        "Joaquín Carreño G.",
        "Krishna Carrillo V.",
        "Bruno Castro B.",
        "Luciano Cermenati M.",
        "Amanda Chiong C.",
        "Gabriel Conejeros B.",
        "Clemente Contardo Cánepa",
        "Bruno Contreras",
        "Renato Contreras S.",
        "Sebastián Cordero E.",
        "Fernando Cordovez",
        "Nicolás Cortés C.",
        "Jorge Cummins",
        "Magdalena Delgado C."
    ],
    "Daniel Radrigán": [
        "Carolina Espinace Fuentes",
        "Benjamín Faunes L.",
        "Aliwen Figueroa P.",
        "Emiliano Figueroa V.",
        "Benjamín Gallardo A.",
        "Andrea Gamarra G.",
        "María José Ganora Gutiérrez",
        "Antonia Garrote G.",
        "Sebastián González F.",
        "Diego G. Leiva",
        "Felipe González Poblete",
        "Mauricio González T.",
        "Macarena Guerra M.",
        "César Hernández A.",
        "José Hugot A.",
        "Cristobal Ignamarca",
        "Thomas Jackson M.",
        "Luciano Jerez A.",
        "Benjamín Jilberto A.",
        "Phillipe Joos F.",
        "Antonia L. Rey",
        "Tomás Lobos T.",
        "Ignacio López A.",
        "Daniela López M.",
        "Álvaro Lozano V.",
        "Tomás Lucero K."
    ],
    "Diego Arias": [
        "Florencia Mebus S.",
        "Salvador Mercado M.",
        "Daniel Meza H.",
        "Cristián Maldonado",
        "Benjamín Minder M.",
        "Alejandro Molina C.",
        "Pascal Steiner",
        "José Morales Mella",
        "Cristóbal Moya Á.",
        "Catalina Muñoz C.",
        "Fernando Muñoz",
        "Benjamin Muñoz",
        "Nelson A. Navarro B.",
        "Rodrigo Norambuena C.",
        "Vicente Núñez Z.",
        "Matías Olate R.",
        "Martín Olguín B.",
        "Florencia Olivares",
        "Juan Ortega M.",
        "Diego Palacios B.",
        "Matias Palma D.",
        "Carolina Pardo D.",
        "Nicole Pérez",
        "Gerald Ponce D.",
        "Isidora Reyes M."
    ],
    "Pablo Skewes": [
        "Patricio Rivera",
        "Bruno Rojas P.",
        "Sebastián Romero C.",
        "Carlos Rubio P.",
        "Diego Ruiz R.",
        "Benjamín Sabag Fuentes",
        "A. León Salas",
        "Agustín Salgado A.",
        "Sebastián A. Salgado",
        "Roberto Salvo Cuitiño",
        "Benjamín S. Robredo",
        "Bárbara Sepúlveda",
        "Franco Serey S.",
        "Benjamín Silva A.",
        "Mauricio Silva",
        "Sebastián Silva",
        "Sebastián Tapia S.",
        "Emilio Torres B.",
        "Felipe Torres C.",
        "Antonio Ugarte C.",
        "Franco Valdebenito S.",
        "Javiera Valdiviezo B.",
        "Matias Videla Meisenbichler",
        "Benjamín Villalobos Torres",
        "Javiera Villanueva S.",
        "Catalina Zambrano Z."
    ]
}
